# -*- coding: utf-8 -*-
"""NLP News Category Project-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahr0NUeUos96lz1P8topcZVXQKwpeGpf
"""

#Bu projede ise TF-IDF modeli ile çalışmaya uygun SMS spam veri seti ile çalışacağız

#TF-IDF modeli kelime bazlı  sınıflandırma yaptığı için bert e göre daha hızlı çalışır ve sonuç
#verir

import pandas as pd

# ; ile ayrıldığı için sep parametresiyle belirtiyoruz
df = pd.read_csv("/content/TurkishSMSCollection.csv", sep=";")

# İlk 5 veriyi göster
df.head()

# Gerekli kütüphaneler
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

# Etiketleri metinle eşle (1 → spam, 2 → ham)
df["label"] = df["Group"].map({1: "spam", 2: "ham"})

# Sadece gerekli sütunları al
df = df[["Message", "label"]]

# Boşlukları temizle
df["Message"] = df["Message"].astype(str).str.strip()
df["label"] = df["label"].astype(str).str.strip()

# Sonucu kontrol et
df.head()

X = df["Message"]
y = df["label"]

# %80 eğitim, %20 test verisi
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# TF-IDF dönüştürücüyü oluştur
vectorizer = TfidfVectorizer()

# Eğitim ve test verisine uygula
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Modeli oluştur
model = MultinomialNB()

# Eğitimi yap
model.fit(X_train_tfidf, y_train)

# Tahmin yap
y_pred = model.predict(X_test_tfidf)

# Sonuçları değerlendir
print("Doğruluk Oranı:", accuracy_score(y_test, y_pred))
print("\nSınıflandırma Raporu:\n", classification_report(y_test, y_pred))

def tahmin_et_interaktif():
    while True:
        print("Çıkmak için 'q' yazıp enter'a basabilirsiniz.")
        mesaj = input("📨 E-posta veya SMS içeriğini giriniz: ")

        if mesaj.lower() == 'q':
            print("Sistemden çıkılıyor.")
            break

        mesaj_tfidf = vectorizer.transform([mesaj])
        tahmin = model.predict(mesaj_tfidf)[0]
        print(f"📌 Tahmin Edilen Sınıf: {tahmin}\n")

# Fonksiyonu çalıştır
tahmin_et_interaktif()